require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - bin/**/*
  NewCops: enable
  SuggestExtensions: false

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/Pluck:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test

Rails/ContentTag:
  Enabled: false # disable as we move to React and begin removing usage

Rails/FilePath:
  EnforcedStyle: arguments

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - Gemfile

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/ArgumentsForwarding:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/update

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Rspec cops
RSpec/AnyInstance:
  Enabled: false # disabled until we determine the right foundation for testing philosophy
RSpec/ContextWording:
  Enabled: false
RSpec/EmptyLineAfterExampleGroup:
  Enabled: false
RSpec/EmptyLineAfterHook:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/HookArgument:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 15
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NotToNot:
  Enabled: false
RSpec/PredicateMatcher:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
